src/SPV/UserBundle/Entity/UserProfile.php
<?php

namespace SPV\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * UserProfile
 *
 * @ORM\Table(name="user_profile")
 * @ORM\Entity(repositoryClass="SPV\UserBundle\Repository\UserProfileRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class UserProfile
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="age", type="integer")
     * @Assert\Type(
     *    type="integer",
     *    message="L'âge {{ value }} ne représente pas un entier !"
     * )
     * @Assert\NotBlank(message="Ce champ doit être saisi !")
     */
    private $age;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=10)
     * @Assert\NotBlank(message="Vous devez choisir votre sexe !")
     * @Assert\Choice(choices = {"m", "f"}, message = "Sélectionnez un sexe valide.")
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar_ext", type="string", length=255, nullable=true)
     */
    private $avatarExt;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="oneshot_description", type="string", length=255)
     * @Assert\NotBlank(message="Vous devez choisir une phrase parmi les propositions !")
     * @Assert\Choice(choices = {"1", "2", "3"}, message = "Sélectionnez une phrase valide.")
     */
    private $oneshotDescription;

    /**
    * @ORM\ManyToOne(targetEntity="SPV\GeolocationBundle\Entity\MapsVille", cascade={"persist"})
    * @ORM\JoinColumn(nullable=false, name="city_id", referencedColumnName="id_ville")
    */
    private $city;

    /**
    * @var datetime
    *
    * @ORM\Column(name="updatedAt", type="datetime")
    */
    protected $updatedAt;

    /*
    * @Assert\Image(maxSize="512k",
    *              maxSizeMessage="L'image ne doit pas déppaser les {{ maxSize }}ko.",
    *              minWidth = 64, minWidthMessage="La largeur de l'image doit faire {{ minWidth }}px au minimum.",
    *              minHeigth = 64, minHeigthMessage="La hauteur de l'image doit faire {{ minHeigth }}px au minimum.",
    *              maxWidth = 2056, maxWidthMessage="La largeur de l'image doit faire {{ maxWidth }}px au maximum.",
    *              maxHeigth = 2056, maxHeigthMessage="La hauteur de l'image doit faire {{ maxHeigth }}px au maximum."
    *
    * )
    */
    private $file;

    //Attribut pour stocker temporairement le nom du fichier
    private $tempFilename;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set age
     *
     * @param integer $age
     *
     * @return UserProfile
     */
    public function setAge($age)
    {
        $this->age = abs($age);

        return $this;
    }

    /**
     * Get age
     *
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * Set gender
     *
     * @param string $gender
     *
     * @return UserProfile
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set avatarExt
     *
     * @param string $avatarExt
     *
     * @return UserProfile
     */
    public function setAvatarExt($avatarExt)
    {
        $this->avatarExt = $avatarExt;

        return $this;
    }

    /**
     * Get avatarExt
     *
     * @return string
     */
    public function getAvatarExt()
    {
        return $this->avatarExt;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return UserProfile
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set oneshotDescription
     *
     * @param string $oneshotDescription
     *
     * @return UserProfile
     */
    public function setOneshotDescription($oneshotDescription)
    {
        $this->oneshotDescription = $oneshotDescription;

        return $this;
    }

    /**
     * Get oneshotDescription
     *
     * @return string
     */
    public function getOneshotDescription()
    {
        return $this->oneshotDescription;
    }

    /**
     * Set city
     *
     * @param \SPV\GeolocationBundle\Entity\MapsVille $city
     *
     * @return UserProfile
     */
    public function setCity(\SPV\GeolocationBundle\Entity\MapsVille $city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return \SPV\GeolocationBundle\Entity\MapsVille
     */
    public function getCity()
    {
        return $this->city;
    }

    public function getDescriptionSentence()
    {
        switch ($this->oneshotDescription) {
          case '1':
            return "Je désire fêter mon célibat comme il se doit !";
            break;

          case '2':
            return "Je désire célébrer mon célibat sobrement.";
            break;

          case '3':
            return "Je désire être surpris(e) ...";
            break;

          default:
            return "";
            break;
        }
    }

    //==========================================================================
    // Evènements pour doctrine et l'upload des images
    //==========================================================================
          public function setFile(UploadedFile $file)
          {
              $this->file = $file;
              $this->updatedAt = new \DateTime();

              //On vérifie si on avait déjà un fichier
              if($this->avatarExt != null)
              {
                  $this->tempFilename = $this->avatarExt;

                  //On réinitialise la photo
                  $this->avatarExt = null;
              }
          }

          public function getFile()
          {
              return $this->file;
          }

          public function getUploadDir() {
              //On retourne le chemin relatif
              return 'img/uploads/avatars';
          }

          protected function getUploadRootDir() {
              // the absolute directory path where uploaded documents should be saved
              return __DIR__ . '/../../../../web/' . $this->getUploadDir();
          }

          /**
           * @ORM\PrePersist()
           * @ORM\PreUpdate()
           */
          public function preUploadImage() {
              // the file property can be empty if the field is not required
              if (null === $this->file) {
                  return;
              }

              //Le nom du fichier est son id, on doit juste stocker son Extension
              //On stocke l'extension du fichier en BDD, d'où avatarExt (ext = extension)
              $this->avatarExt = $this->file->guessExtension();
          }

          /**
           * @ORM\PostPersist()
           * @ORM\PostUpdate()
           */
          public function upload()
          {
              //Si jamais il n'y a pas de photo champ facultatif
              if (null === $this->file) {
                  return;
              }

              //Si on avait un ancien fichier on le supprime
              if($this->tempFilename != null)
              {
                  $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
                  if(file_exists($oldFile))
                  {
                      unlink($oldFile);
                  }
              }

              //On déplace le fichier envoyé dans le répertoire de notre choix
              $this->file->move(
                $this->getUploadRootDir(),
                $this->id . '.' . $this->avatarExt // le nom du fichier créé id + extension
              );
          }

          /**
           * @ORM\PreRemove()
           */
          public function preRemoveUpload()
          {
              //On sauvegarde temporairement le nom du fichier
              $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->avatarExt;
          }

          /**
           * @ORM\PostRemove()
           */
          public function removeUpload()
          {
              //En post remove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
              if(file_exists($this->tempFilename))
              {
                  //On supprime le fichier
                  unlink($this->tempFilename);
              }
          }

          public function getWebPath()
          {
              return $this->getUploadDir() . '/' . $this->getId() . '.' . $this->getAvatarExt();
          }

          public function getRelativeWebPath()
          {
              return $this->getUploadRootDir() . '/' . $this->getId() . '.' . $this->getAvatarExt();
          }
    //==========================================================================

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return UserProfile
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    //==========================================================================
    // Connaître l'orientation de l'image et déterminé dans quel sens l'afficher

src/SPV/UserBundle/Form/UserProfileType.php
<?php
// src/AppBundle/Form/RegistrationType.php

namespace SPV\UserBundle\Form;

use FOS\UserBundle\Util\LegacyFormHelper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use SPV\UserBundle\Form\FormType\DescriptionSentenceType;
use SPV\UserBundle\Form\FormType\GenderType;

class UserProfileType extends AbstractType
{
      public function buildForm(FormBuilderInterface $builder, array $options)
      {
          $builder->add('age', IntegerType::class, array('label' => 'Indiquez votre âge'))
                  ->add('gender', GenderType::class, array('label' => 'Indiquez votre sexe',
                                                           'expanded' => true,
                                                           'multiple' => false))
                  ->add('description', TextareaType::class, array('label' => 'Description de votre profil',
                                                                          'attr' => array('rows' => 3),
                                                                          'required' => false))
                  ->add('oneshotDescription', DescriptionSentenceType::class, array('label' => 'Choisissez la phrase qui vous correspond le mieux :',
                                                                                    'expanded' => true,
                                                                                    'multiple' => false))
                  ->add('file', FileType::class, array('required' => false, 'label' => 'Photo (format: jpeg, png, gif et tiff)'))
          ;
      }

      public function configureOptions(OptionsResolver $resolver)
      {
          $resolver->setDefaults(array(

          ));
      }

      public function getBlockPrefix()
      {
          return 'user_profile_registration';
      }
}

src/SPV/UserBundle/Controller/UserProfileController.php
<?php

namespace SPV\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use SPV\UserBundle\Form\UserProfileType;
use SPV\UserBundle\Entity\UserProfile;

class UserProfileController extends Controller
{
    public function completeAction(Request $request)
    {
        $connectedUser = $this->getUser();
        $userProfile = new UserProfile();

        $city_term = null;

        if($connectedUser != null)
        {
            //Si le profil est déjà complété alors c'est une modification
            //On récupère le user profile existant et la ville existante
            if($connectedUser->getProfileIsCompleted() != false)
            {
                $userProfile = $connectedUser->getUserProfile();
                //On met le nom de la ville qu'on avait
                $city_term = $userProfile->getCity()->getNom();
            }
        }

        $form = $this->createForm(UserProfileType::class, $userProfile);

        //Toutes le villes trouvées.
        //Ce tableau sera afffiché sous forme de liste
        //Si on trouve plusieurs villes ou codes postals
        $found_cities = array();

        //Erreurs liées à la ville
        $error_cities = array();

        if($connectedUser != null)
        {
            if($request->getMethod() == 'POST')
            {
                //Récupération du nom de la ville
                $city_term =  $request->request->get('city_term');
                $city_id = $request->request->get('cities');

                $isCityTermOk = $city_term != "" || $city_term != null;

                if($isCityTermOk != true && $city_id == "")
                {
                    array_push($error_cities, "Entrez une ville s'il vous plait !");
                }

                if($isCityTermOk || $city_id != "")
                {
                    //On fait le lien entre la requête et le formulaire Request <=> Form
                    $form->handleRequest($request);

                    $em = $this->getDoctrine()->getManager();
                    $repo_city = $em->getRepository("GeolocationBundle:MapsVille");
                    $found_cities = $repo_city->getCityByNameOrPostalCode($city_term);

                    if($found_cities == null && $city_id == "")
                    {
                        array_push($error_cities, "La ville que vous avez saisie n'est pas répertoriée dans notre base de données. Saisissez une ville proche de la votre s'il vous plait !");
                    }

                    //Par défaut la ville est null
                    $city = null;

                    //Si on dans les villes trouvés il n y en a qu'une alors on prend celle-ci
                    //Si le city_id n'est vide alors on a choisi une ville dans la liste.
                    //alors on la cherche dans la BDD au cas où et on prend celle-ci
                    if(count($found_cities) == 1)
                    {
                        $city = $found_cities[0];
                    }
                    else if($city_id != "")
                    {
                        $city = $repo_city->findOneBy(array('id' => $city_id));
                    }

                    if($form->isValid() && count($error_cities) == 0 && $city != null)
                    {
                        $userProfile->setCity($city);

                        //Si l'utilisateur n'à pas complété son profil alors on persist et on met à true
                        // le profil a bien été complété
                        if($connectedUser->getProfileIsCompleted() == false)
                        {
                            $em->persist($userProfile);
                            $connectedUser->setProfileIsCompleted(true);
                        }

                        $userProfile->setUpdatedAt(new \DateTime());

                        $connectedUser->setUserProfile($userProfile);

                        $em->flush();

                        //Redirection vers la page d'accueil
                        return $this->redirect($this->generateUrl('homepage'));
                    }
                }
            }
        }

        return $this->render('UserBundle:UserProfile:complete.html.twig',
                             array('form' => $form->createView(), 'cities' => $found_cities, "error_cities" => $error_cities,
                                    'city_term' => $city_term));
    }


    public function showUserAction($username)
    {
        $em = $this->getDoctrine()->getManager();
        //On récupère le destinataire en fonction du nom d'utilisateur
        $user = $em->getRepository("UserBundle:User")
                            ->findOneBy(array('username' => $username));

        if($user != null)
        {
            return $this->render('UserBundle:UserProfile:show.html.twig',
                                array("user" => $user));
        }
        else {
            return $this->render('UserBundle:UserProfile:show.html.twig',
                                array("error" => "L'utilisateur " . $username . " n'existe pas !"));
        }
    }
}

src/SPV/UserBundle/Resources/views/UserProfile/complete.html.twig
{% extends "::base.html.twig" %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('css/autocomplete/jquery-ui-1.8.18.custom.css') }}">
{% endblock %}

{% block title %}Compléter votre profil{% endblock %}

{% block body %}
  <section class="first_section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Complétez votre profil</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
          <!--<h4 class="no_uppercase text-center">C'est le moment que vous allez préférer !</h4>-->
          <h4 class="no_uppercase text-center">Maintenant c'est à vous de jouer !</h4>
          <p class="text-center">
            Créez votre profil ici. <br />
            Soyez créatif, mais surtout soignez l'orthographe et la présentation de votre description.
          </p>
        </div>
        <div class="row">
          {% form_theme form '::form_base.html.twig' %}

          {{ form_start(form, {'method': 'post', 'action': path('user_complete_profile'), 'attr': {'class': 'user_complete_profile', 'id': 'search-form'}}) }}
              <div class="form-group">
                {{ form_label(form.age) }} {{ form_widget(form.age) }}
                {{ form_errors(form.age) }}
              </div>

              <div class="form-group">
                {{ form_label(form.gender) }} {{ form_widget(form.gender) }}
                {{ form_errors(form.gender) }}
              </div>

              <div class="form-group">
                {{ form_label(form.oneshotDescription) }} {{ form_widget(form.oneshotDescription) }}
                {{ form_errors(form.oneshotDescription) }}
              </div>

              <div class="form-group">
                <lablel class="control-label required">Nom ou code postal de la ville</label>
                <input class="form-control" type="text" id="searchbox" name="city_term"
                       value="{% if city_term != "" %}{{ city_term }}{% endif %}"/>
                <div id="city-list">
                </div>
                {% if error_cities|length > 0 %}
                    <span class="help-block">
                      <ul class="list-unstyled">
                        {% for error in error_cities %}
                            <li>
                              <span class="glyphicon glyphicon-exclamation-sign"> </span> {{ error }}
                            </li>
                        {% endfor %}
                      </ul>
                    </span>
                {% endif %}
              </div>

              {% if cities|length > 1 %}
                <div class="form-group">
                  <lablel class="control-label required">Plusieurs ville ont été trouvées, veuillez selectionnez votre ville dans la liste</label>

                  {# affichage de toutes les villes dans une liste #}
                  <select class="form-control" id="sel1" name="cities">
                    {% for city in cities %}
                      <option  value="{{ city.id }}">{{ city.nom }} | {{ city.cp }}</option>
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="form-group">
                {{ form_label(form.file) }} {{ form_widget(form.file) }}
                {{ form_errors(form.file) }}
              </div>

              <div class="form-group">
                {{ form_label(form.description) }} {{ form_widget(form.description) }}
                {{ form_errors(form.description) }}
              </div>

              <div>
                  <input class="btn btn-success btn-lg" type="submit" value="Valider" />
              </div>
          {{ form_end(form) }}
        </div>
      </div>
    </section>
{% endblock %}

{% block javascripts %}
  <script>
    var TWIG = {};
    TWIG.path = "{{ url('geolocation_search_city') }}"
  </script>

  <script type="text/javascript" src="{{ asset('js/autocomplete/jquery-ui-1.8.18.custom.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('js/autocomplete/attach-autocomplete.js') }}"></script>


{% endblock %}

src/SPV/UserBundle/Resources/views/UserProfile/show.html.twig
{% extends "::base.html.twig" %}

{% block title %}Profil de {{ user.username|capitalize }}{% endblock %}

{% block body %}
<section class="first_section">
  <div class="container">
    <div class="row">
      {% if user is defined %}
          <div class="col-md-8 col-xs-10">
            <div class="well panel panel-default well_spv">
              <div class="panel-body">
                <div class="row">
                  <div class="col-xs-12 col-sm-4 text-center">
                      {% include 'UserBundle:UserProfile:temp_image.html.twig' with
                         {'imgCircle': true, 'imgThumbnail':true, 'imgResponsive':true, "centerBlock":true} %}
                  </div>
                  <!--/col-->
                  <div class="col-xs-12 col-sm-8">
                    <h2 class="no_uppercase">{{ user.username|capitalize }}</h2>
                    <p>
                      {% if user.userProfile.gender != null %}
                        {% if user.userProfile.gender == "m" %}
                          Homme
                        {% else %}
                          Femme
                        {% endif %}
                        {# si on a l'age en même temps que le sexe on rajoute le de #}
                        {% if user.userProfile.age != null %}
                          de
                        {% endif %}
                      {% endif %}

                      {% if user.userProfile.age != null %}
                        {{ user.userProfile.age }} ans
                      {% endif %}
                    </p>
                    <p><strong><span class="glyphicon glyphicon-map-marker"></span></strong> {{ user.userProfile.city.nom }} ({{ user.userProfile.city.cp }}) </p>
                    <p><strong>A propos: </strong>
                      {{ user.userProfile.descriptionSentence }}
                    </p>
                  </div>
                  <!--/col-->
                  <div class="clearfix"></div>
                  <div class="more_space">
                    <p class="text-justify">
                      {% if user.userProfile.description != null %}
                          {{ user.userProfile.description }}
                      {% else %}
                        <i>Aucune description</i>
                      {% endif %}
                    </p>
                  </div>
                </div>
                <!--/row-->
                <div class="row">
                  {% if user.id == app.user.id %}
                      <div class="col-md-4 col-lg-4">
                        <a href="{{ url('fos_user_profile_edit') }}" class="btn btn-default btn-block" role="button">
                          Modifier les identifiants
                        </a>
                      </div>
                      <div class="col-md-4 col-lg-4">
                        <a href="{{ url('user_complete_profile') }}" class="btn btn-primary btn-block" role="button">
                          Modifier votre profil
                        </a>
                      </div>
                      <div class="col-md-4 col-lg-4">
                        <a href="#" onclick="alert_danger();" class="btn btn-danger btn-block" role="button">
                          Supprimer votre compte
                        </a>
                      </div>
                  {% else %}
                    <a href="{{ url('message_send', {'user_id':user.id}) }}" class="btn btn-primary btn-block" role="button">
                      <span class="glyphicon glyphicon-envelope"></span> Envoyer un message
                    </a>
                  {% endif %}
                </div>
              </div>
              <!--/panel-body-->
            </div>
            <!--/panel-->
          </div>
          <!--/col-->
      {% endif %}
      {% if error is defined %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
    </div>
  <!--/row-->
  </div>
  <!--/container-->
</section>
{% endblock %}

{% block javascripts %}
    <script>
      function alert_danger() {
        var r = confirm("Êtes-vous sûr ? Cette action est irréversible !");
        if (r == true) {
            window.location = "{{ url('user_remove') }}";
        } else {

        }
      }
    </script>
{% endblock %}

src/SPV/UserBundle/Resources/views/UserProfile/temp_image.html.twig
{% if user.userProfile != null %}
  {% set rotate = "" %}

  {% if user.userProfile.getImageRotation != null %}
    {% set rotate = "fa-rotate-" ~ user.userProfile.getImageRotation  %}
  {% else %}

  {% endif %}

  {% if imgCircle is defined %}
    {% set imgCircle = "img-circle"  %}
  {% else %}
    {% set imgCircle = ""  %}
  {% endif %}

  {% if centerBlock is defined %}
    {% set centerBlock = "center-block"  %}
  {% else %}
    {% set centerBlock = ""  %}
  {% endif %}

  {% if imgThumbnail is defined %}
    {% set imgThumbnail = "img-thumbnail"  %}
  {% else %}
    {% set imgThumbnail = ""  %}
  {% endif %}

  {% if imgResponsive is defined %}
    {% set imgResponsive = "img-responsive"  %}
  {% else %}
    {% set imgResponsive = ""  %}
  {% endif %}

  {% if user.userProfile.avatarExt != null %}
      <img src="{{ asset(user.userProfile.webPath) }}" alt=""
            class="{{ centerBlock }} {{ imgCircle }} {{ imgThumbnail }} {{ imgResponsive }} {{ rotate }}"
            {% if width is defined %}
              width="{{ width }}"
            {% endif %}
            >
  {% else %}
       <img src="{{ asset('img/coeur.png') }}" alt=""
             class="{{ centerBlock }} {{ imgCircle }} {{ imgThumbnail }} {{ imgResponsive }}"
             {% if width is defined %}
               width="{{ width }}"
             {% endif %}
             >
  {% endif %}
{% endif %}